### ISSUE TITLE
version number for sword package should ignore hyphen

### ISSUE THREAD

**Issue by timsoftgit** [AMDmi3/repology#138]
this entry shows the opensusie 1.7.5-a1 version as more recent than the 1.7.5a1 version used by Arch and Slackbuilds.org although they are all the same. A sed 's/-//g' on the version strings before the compare should make the comparison match.

**Comment by AMDmi3** [comment]
The comparison actually requires a bit more clever approach. First, there's tilda, not a hyphen, and you can't just remove it as e.g. ```1.2.3~1``` will then become ```1.2.31``` which is not what we want.

Hyphens are handled properly by repology, btw: ```1.7.5-a1``` and ```1.7.5a1``` are compared as equal, because ```-``` is treated as a separator and ```5a1``` is treated as ```5.a1```. The problem in that tilda is not (yet) treated as a separator. I wanted to fix this for some time, now is a perfect chance.

**Comment by timsoftgit** [comment]
thanks for the fix
