### ISSUE TITLE
Add support for AUR

### ISSUE THREAD

**Issue by AMDmi3** [AMDmi3/repology#7]
How do I download a single-file AUR index (the one pacman uses?) or whole AUR as a single repository? No idea for now. As last resort, AUR website may be scrapped.

**Comment by alexws54tk** [comment]
### Searching

The AUR web interface can be found at https://aur.archlinux.org/, and an interface suitable for accessing the AUR from a script can be found at https://aur.archlinux.org/rpc.php.
Queries search package names and descriptions via a MySQL LIKE comparison. This allows for more flexible search criteria (e.g. try searching for `tool%like%grep` instead of `tool like grep`). If you need to search for a description that contains `%`, escape it with `\%`.

### How can I obtain a list of all AUR packages?
 
* https://aur.archlinux.org/packages.gz
* Use `aurpkglist` from [python3-aur](https://aur.archlinux.org/packages/python3-aur/)

From [Arch Wiki](https://wiki.archlinux.org/index.php/Arch_User_Repository)

**Comment by AMDmi3** [comment]
> https://aur.archlinux.org/packages.gz

Nice! And then we can download packages in batches via

```
https://aur.archlinux.org/rpc/?v=5&type=info&arg[]=package1&arg[]=package2...
```

Confirmed to work with 100 packages. Gotta implement this and look if AUR is usable at all, as I'm worried that it'll contain too many fake versions constructed of revision numbers, dates and git commits.

**Comment by CarbonFixer** [comment]
> I'm worried that it'll contain too many fake versions constructed of revision numbers, dates and git commits

I would omit all packages with a VCS suffix (-cvs, -svn, -hg, -darcs, -bzr, and -git should cover all of them).

**Comment by AMDmi3** [comment]
Support added, available in test.repology.org.
